using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace SMT.Utilities.FogBugz.Json.ObjectInterfaces
{
	public enum FogbugzApiErrorCodes
	{
		FB_NOT_INITIALIZED = 0,
		FB_NOT_PROPER_PASSWORD = 1,
		FB_MULTIPLE_MATCHES = 2,
		FB_NOT_LOGGED_ON = 3,
		FB_API_ARGUMENT_REQUIRED = 4,
		FB_NO_BUG_NUM = 5,
		FB_API_ACTION_NOT_PERMITTED = 6,
		FB_TIME_TRACKING_PROBLEM = 7,
		FB_NO_PERMISSION_TO_CREATE_CASE = 8,
		FB_CASE_HAS_CHANGED = 9,
		FB_SEARCH_PROBLEM = 10,
		SKIPPED_11 = 11,
		FB_WIKI_CREATION_PROBLEM = 12,
		FB_API_INSUFFICIENT_PERMISSIONS = 13,
		FB_WIKI_LOAD_ERROR = 14,
		FB_TEMPLATE_ERROR = 15,
		FB_WIKI_COMMIT_ERROR = 16,
		FB_NO_SUCH_PROJECT = 17,
		FB_NO_SUCH_USER = 18,
		FB_AREA_CREATION_PROBLEM = 19,
		FB_FIX_FOR_CREATION_PROBLEM = 20,
		FB_PROJECT_CREATION_PROBLEM = 21,
		FB_USER_CREATION_PROBLEM = 22,
		FB_PROJECT_PERCENT_TIME_PROBLEM = 23,
		FB_API_NO_SUCH_FIX_FOR = 24,
		FB_VIOLATES_FIX_FOR_EXECUTION_ORDER = 25,
		FB_UNKNOWN_ERROR_DURING_COMMIT = 26,
		FB_API_NO_SUCH_COMMAND = 27,
		FB_ACCOUNT_IN_MAINTENANCE_MODE = 28,
		FB_TWO_FACTOR_ENABLED = 29,
		FB_API_SEARCH_MAX = 30,
		FB_API_NO_SUCH_HOLIDAY = 31,
		FB_UNABLE_TO_PARSE_DATE = 32,
		FB_API_PERMISSION_GROUP_NAME_EXISTS = 33,
		FB_API_UNRECOGNIZED_ACL_SECTION = 34,
		FB_API_UNRECOGNIZED_PERMISSION = 35,
		FB_API_UNRECOGNIZED_PERMISSION_GROUP = 36,
		FB_API_ERROR_WITH_RETROEDIT = 37,
	}
}
